model:
  name: bert-base-uncased
  type: transformers.BertForSequenceClassification

  params:
    num_classes : 2
    max_length : 256
    batch_size : 16
    num_epochs : 2
    learning_rate : 1e-5
    early_stopping : 2


  optimizer: torch.optim.AdamW

  
pipeline:
  run_preprocessing: false
  run_training: true

data:
  raw_text_dir: "data/raw"
  interim_path: "data/interim/chunked_256"
  target_column: label

preprocessing:
  chunking:
    enabled: false
    max_words: 128
    overlap: 1

  embeddings:
    enabled: true
    model_name: "all-MiniLM-L6-v2"

training:
  test_size: 0.2
  stratify: true

  cross_validation:
    enabled: false   # enable later if needed
    folds: 5
    scoring: roc_auc

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc

output:
  base_dir: results
  save_model: true

df: "/Users/yavuzlule/Desktop/bsc-relish/data/interim/chunked_256/2026-04-30_15-29-41/dataset.parquet"