model:
  name: distilbert-base-uncased
  type: transformers.DistilBertForSequenceClassification

  params:
    num_classes: 2
    max_length: 256
    batch_size: 16
    num_epochs: 1
    learning_rate: 1e-5

  optimizer: torch.optim.AdamW

pipeline:
  run_preprocessing: true
  run_training: true

data:
  raw_text_dir: "data/raw"
  interim_path: "data/interim"
  target_column: label

preprocessing:
  chunking:
    enabled: true
    max_words: 256
    overlap: 1

  embeddings:
    enabled: false
    model_name: "all-MiniLM-L6-v2"

training:
  test_size: 0.2
  stratify: true

  cross_validation:
    enabled: false
    folds: 5
    scoring: roc_auc

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc

output:
  base_dir: results
  save_model: true

df: "/Users/yavuzlule/Desktop/bsc-relish/data/interim/2026-04-29_00-33-21/dataset.parquet"