model:
  name: logistic_regression
  type: sklearn.linear_model.LogisticRegression

  params:
    C: 1.0
    solver: saga
    max_iter: 500
    class_weight: "balanced"
    random_state: 42

training:
  test_size: 0.2
  stratify: true

  cross_validation:
    enabled: false   # enable later if needed
    folds: 5
    scoring: roc_auc

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc

output:
  base_dir: results
  save_model: true

data:
  raw_text_dir: "data/raw"
  interim_path: "data/interim"
  target_column: label

df: "/Users/yavuzlule/Desktop/bsc-relish/data/interim/2026-04-20_12-42-25/dataset.parquet"