data:
  raw_text_dir: "data/raw"
  label_map: {
            "archive-americana-cookbook-download-desc": 1,
            "archive-americana-download-desc": 1,
            "archive-americana-recipe-download-desc": 1,
            "archive-americana-fiction-literature-technology-download-desc": 0
        }
  train_path: "data/interim"
  target_column: label
  limit_files:
    enabled: false
    max_files: 32


preprocessing:
  chunking:
    enabled: true
    max_words: 256
    overlap: 1

  embeddings:
    enabled: true
    model_name: "all-MiniLM-L6-v2"

pipeline:
  run_preprocessing: true
  run_training: false

