# =========================
# DATA CONFIGURATION
# =========================
data:
  raw_path: data/raw
  interim_path: data/interim

  # label mapping for supervised tasks
  label_map: {
            "wiki_chunks-test": 0
        }

  limit_files:
    enabled: false
    #max_files: 5

  encoding: utf-8
  recursive: true
  drop_empty: true


df: "/media/M2_disk/yavuz/bsc-masters-thesis/data/test/multilingual_test.parquet"

# =========================
# PREPROCESSING PIPELINE
# =========================
model:
  name: sentence-transformers/all-MiniLM-L6-v2
  type: sentence_transformer

preprocessing:

  # -------- CHUNKING --------
  chunking:
    enabled: true
    strategy: word  # options: word | char | sentence (future)
    max_words: 256
    overlap: 0       # future extension

  # -------- CLEANING --------
  cleaning:
    enabled: false
    lowercase: false
    remove_punctuation: false
    strip_whitespace: true

  embeddings:
    enabled: false

    model:
      name: sentence-transformers/all-MiniLM-L6-v2
      type: sentence_transformer

    batch_size: 32
    normalize: true



# =========================
# OUTPUT / STORAGE
# =========================
output:

  dataset_name: processed_text_dataset

  store:
    format: parquet        # parquet | csv | pickle
    compression: snappy
    row_group_size: 100000

  save_intermediate:
    chunked: true
    embeddings: true


# =========================
# EXECUTION SETTINGS
# =========================
execution:

  device: cuda   # cpu | cuda

  logging:
    level: INFO
    show_progress: true

  reproducibility:
    seed: 42