model:
  name: svm
  type: sklearn.svm.SVC

  params:
    C: 1.0
    kernel: rbf
    gamma: scale
    class_weight: balanced
    probability: true
    random_state: 42

training:
  test_size: 0.2
  stratify: true


evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc

output:
  base_dir: results
  save_model: true

data:
  raw_text_dir: "data/raw"
  interim_path: "data/interim"
  target_column: label


#df: "/media/M2_disk/yavuz/bsc-masters-thesis/data/train/preprocessed_miriam_corpus_train.parquet"
df: "/media/M2_disk/yavuz/bsc-masters-thesis/data/test/multilingual_test.parquet"
